### ISSUE TITLE
Please add CVPR 2024 paper "Hourglass Tokenizer for Efficient Transformer-Based 3D Human Pose Estimation"

### ISSUE THREAD

**Issue by Vegetebird** [extreme-assistant/CVPR2024-Paper-Code-Interpretation#104]
Paper title: Hourglass Tokenizer for Efficient Transformer-Based 3D Human Pose Estimation
Paper link: https://arxiv.org/pdf/2311.12028.pdf
Code link: https://github.com/NationalGAILab/HoT

**Comment by maweifei** [comment]
别去连众QQ了，来这里，http://www.66D47.TK ，真金白银，太有意思了，咱班的兄弟们都在这里玩
